spring:
  thymeleaf:
    prefix: classpath:/templates/
  # 后缀
    suffix: .html
  # 模板格式
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

spring.application.name: luozijian-service
server.port: 8080
#------------日志-------------------
logging:
  config: classpath:logback-spring.xml
  path: /data/deploy/log/${spring.application.name}
  level:
    com.example.demo.mapper: DEBUG


#-------------mybatis---------------
mybatis:
  mapper-location: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.example.demo.common.mapper.BaseMapper
  identity: MYSQL

spring.devtools.restart.enabled: true


#--------------eureka------------------
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      #向三个服务端分别注册
      defaultZone: http://192.168.1.61:20001/eureka/,http://192.168.1.63:20002/eureka/  #eureka服务的位置
    register-with-eureka: true #向eureka注册服务
    fetch-registry: true #拉取注册表的本地副本